# 使用 alpine 作为基础镜像
FROM alpine:latest

# 将时区设置为 Asia/Shanghai
RUN apk --no-cache add tzdata && \
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && \
    echo "Asia/Shanghai" > /etc/timezone && \
    apk del tzdata

# 将应用程序复制到容器内
COPY ./temp/linux_amd64/xyhelper-gpt /usr/local/bin/xyhelper-gpt

# 设置环境变量
ENV PORT=8080

# 暴露端口
EXPOSE $PORT

# 启动应用程序
CMD ["xyhelper-gpt"]